# Generated by Django 3.0 on 2019-12-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='context',
            new_name='content',
        ),
    ]
